services:
  m3u8xm:
    build: .
    container_name: m3u8xm
    ports:
      - 8888:8888
    volumes:
      - ./config.ini:/app/config.ini
    restart: unless-stopped
    networks:
      - m3u8xm

networks:
  m3u8xm:
