name: Build and release binaries

on: [push]

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.12
        uses: actions/setup-python@v5  
        with:
          python-version: '3.12'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile sxm.py
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4  
        with:
          name: sxm-windows.exe
          path: dist/sxm.exe

  build-macos:
    name: Build macOS Universal Binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build universal macOS binary
        run: |
          pyinstaller --onefile sxm.py --name sxm-macos --target-arch universal2
      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: sxm-macos
          path: dist/sxm-macos

  release:
    name: Create GitHub Release
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Windows EXE
        uses: actions/download-artifact@v4
        with:
          name: sxm-windows.exe
      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: sxm-macos
      - name: Create Release & upload assets
        uses: ncipollo/release-action@v1  
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            sxm-windows.exe:dist/sxm.exe
            sxm-macos:dist/sxm-macos
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
